local QBCore = exports['qb-core']:GetCoreObject()

-- blip with coords // Copy and paste to add more random blips
Citizen.CreateThread(function()
    local blip = AddBlipForCoord(  Config.Blip.x, Config.Blip.y, Config.Blip.z)
    SetBlipSprite (blip, Config.Blip.sprite)
    SetBlipDisplay(blip, Config.Blip.display)
    SetBlipScale  (blip, Config.Blip.scale)
    SetBlipColour (blip, config.Blip.color)
    SetBlipAsShortRange(blip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString("Crack House")
    EndTextCommandSetBlipName(blip)
end)

--- blip with config // Copy and paste to add more random blips 
Citizen.CreateThread(function()
    local blip = AddBlipForCoord(  Config.Blip2.x, Config.Blip2.y, Config.Blip2.z)
    SetBlipSprite (blip, Config.Blip2.sprite)
    SetBlipDisplay(blip, Config.Blip2.display)
    SetBlipScale  (blip, Config.Blip2.scale)
    SetBlipColour (blip, config.Blip2.color)
    SetBlipAsShortRange(blip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString("Crack House")
    EndTextCommandSetBlipName(blip)
end)
